---
title: '[딥다이브] - 45. 프로미스'
date: '2024-10-18T00:00:00'
tags: ['javascript', 'book', 'deepdive']
draft: false
summary: 45. 프로미스
layout: PostSimple
---

전통적인 콜백 패턴은 콜백 헬로 가독성이 나쁘고, 에러의 처리가 곤란하며 여러 개의 비동기 처리에 한계가 있다.  
ES6에서 프로미스를 도입해 단점을 보완하고, 비동기 처리 시점을 명확하게 표현할 수 있게 되었다.

## 45.1. 비동기 처리를 위한 콜백 패턴의 단점

### 45.1.1. 콜백 헬

```js
let g = 0

// 비동기 함수인 setTimeout 함수는 콜백 함수의 처리 결과를 외부로 반환하거나 상위 스코프의 변수에 할당하지 못한다.
setTimeout(() => (g = 100), 0)
console.log(g) // 0
```

비동기 함수를 호출하면 함수 내부의 비동기로 동작하는 코드가 완료되지 않아도 종료된다. 비동기 함수 내부의 비동기로 동작하는 코드는 비동기 함수가 종료된 이후에 완료된다. 비동기 함수 내부의 비동기로 동작하는 코드에서 처리 결과를 외부로 리턴하거나 상위 스코프의 변수에 할당하면 기대한 대로 동작하지 않는다.

setTimeout은 비동기 함수다. setTimeout을 호출하면 콜백 함수를 호출 스케줄링한 후, 타이머 id를 리턴하고 즉시 종료된다. 즉, 비동기 함수인 setTimeout의 **콜백 함수**는 setTimeout **함수가 종료된 이후에 호출된다.**

```js
let todos

const get = (url) => {
  const xhr = new XMLHttpRequest()
  xhr.open('GET', url)
  xhr.send()

  xhr.onload = () => {
    if (xhr.status === 200) {
      todos = JSON.parse(xhr.response)
    } else {
      console.error(`${xhr.status} ${xhr.statusText}`)
    }
  }
}

get('https://jsonplaceholder.typicode.com/posts/1')
console.log(todos) // undefined
```

onload 이벤트 핸들러가 비동기로 동작하므로 get 함수도 비동기 함수다. 비동기 함수인 get 함수 내부의 onload 이벤트 핸들러는 get 함수가 종료된 이후에 실행된다.

서버로부터 응답이 도착하면 xhr 객체에서 load 이벤트가 발생하는데, xhr.onload 핸들러 프로퍼티에 바인딩한 이벤트 핸들러가 즉시 실행되는 것이 아니다. xhr.onload 이벤트 핸들러는 태스크 큐에서 대기하다가, 콜 스택이 비면 이벤트 루프에 의해 콜 스택으로 푸시되어 실행된다.

**비동기 함수는 비동기 처리 결과를 외부에 리턴할 수 없고, 상위 스코프의 변수에 할당할 수 없다. 비동기 함수의 처리 결과에 대한 후속 처리는 비동기 함수 내부에서 수행해야 한다.** 성공/실패 시 호출될 콜백 함수를 전달하는 것이 일반적

**콜백 헬**: 비동기 처리 결과를 가지고 다시 비동기 함수를 호출하면 콜백 함수 호출이 중첩되어 복잡도가 높아진다.

```js
get('/step1', (a) => {
  get(`/step2/${a}`, (b) => {
    get(`/step3/${b}`, (c) => {
      get(`/step4/${c}`, (d) => {
        console.log(d)
      })
    })
  })
})
```

### 45.1.2. 에러 처리의 한계

```js
try {
  setTimeout(() => throw new Error('Error'), 1000)
} catch (e) {
  console.error(e) // 캐치하지 못함
}
```

에러는 호출자 방향으로 전파되는데, setTimeout의 콜백 함수를 호출한 것은 setTimeout이 아니다. 콜백 함수가 발생시킨 에러는 catch 블록에서 캐치되지 않는다.

## 45.2. 프로미스의 생성

`Promise` 생성자 함수를 new 연산자와 함께 호출하면 프로미스 객체를 생성한다. Promise는 표준 빌트인 객체다. `Promise` 생성자 함수는 비동기 처리를 수행할 콜백 함수로 resolve와 reject 함수를 전달받는다.

비동기 처리가 성공하면 resolve 함수를, 실패하면 reject 함수를 호출한다.

```js
const promise = new Promise((resolve, reject) => {
  if(비동기 처리 성공) resolve('result')
  else reject('failure reason')
})
```

프로미스는 다음과 같은 비동기 처리 상태 정보를 갖는다.

| 프로미스의 상태 정보     | 의미                                  | 상태 변경 조건                   |
| ------------------------ | ------------------------------------- | -------------------------------- |
| pending                  | 비동기 처리가 아직 수행되지 않은 상태 | 프로미스가 생성된 직후 기본 상태 |
| fulfilled (settled 상태) | 비동기 처리가 수행된 상태(성공)       | resolve 함수 호출                |
| rejected (settled 상태)  | 비동기 처리가 수행된 상태(실패)       | reject 함수 호출                 |

- 생성 직후: pending 상태
- 비동기 처리 성공: resolve 함수를 호출해 프로미스를 fulfilled 상태로 변경
- 비동기 처리 실패: reject 함수를 호출해 프로미스를 rejected 상태로 변경

프로미스의 상태는 resolve 또는 reject 함수를 호출하는 것으로 결정된다.

## 45.3. 프로미스의 후속 처리 메서드

then, catch, finally는 모두 항상 프로미스를 리턴한다.

### 45.3.1. Promise.prototype.then

then 메서드는 두 개의 콜백 함수를 인수로 전달받는다. 첫 번째 콜백 함수는 성공 처리 콜백 함수, 두 번째 콜백 함수는 실패 처리 콜백 함수다.  
콜백 함수가 프로미스를 리턴하면 그 프로미스를 그대로 리턴하고, 프로미스가 아닌 값을 리턴하면 암묵적으로 resolve 또는 reject하여 프로미스를 생성해 리턴한다.

### 45.3.2. Promise.prototype.catch

catch 메서드의 콜백 함수는 프로미스가 rejected 상태인 경우만 호출된다.

### 45.3.3. Promise.prototype.finally

finally 메서드의 콜백 함수는 프로미스의 성공/실패와 관계없이 무조건 한 번 호출된다.

## 45.4. 프로미스의 에러 처리

catch 메서드가 가독성이 좋고 명확하므로 에러 처리는 then이 아닌 catch에서 하는 것을 권장한다.

## 45.5. 프로미스 체이닝

then, catch, finally 메서드는 언제나 프로미스를 리턴하므로 연속적으로 호출할 수 있다. 이를 `프로미스 체이닝`이라 한다.

프로미스도 가독성이 좋지 않은 콜백 패턴을 사용하는데, 이는 ES8에서 도입된 `async/await`를 통해 해결할 수 있다.

## 45.6. 프로미스의 정적 메서드

Promise는 5가지 정적 메서드를 제공한다.

### 45.6.1. Promise.resolve / Promise.reject

`Promise.resolve`와 `Promise.reject`는 이미 존재하는 값을 래핑하여 프로미스를 생성하기 위해 사용한다.

`Promise.resolve`는 전달받은 값을 resolve하는 프로미스를, `Promise.reject`는 값을 reject하는 프로미스를 생성한다.

### 45.6.2. Promise.all

`Promise.all`은 여러 개의 비동기 처리를 모두 병렬 처리할 때 사용한다.

순차적으로 처리하면 앞선 비동기 처리가 완료되어야 다음 비동기 처리를 수행하므로 여러 비동기 처리시간의 합이 총 소요 시간이 된다. 그러나 병렬 처리를 하면 가장 오래 걸리는 비동기 처리시간이 총 소요 시간이 된다.

`Promise.all`은 프로미스를 요소로 갖는 배열 등의 이터러블을 인수로 전달받고, 모든 프로미스가 모두 fulfilled 상태가 되면 모든 처리 결과를 배열에 담아 새로운 프로미스를 리턴한다. 이 때, 처리 순서는 보장된다.

`Promise.all`은 인수로 전달받은 배열의 프로미스가 하나라도 rejected 상태가 되면 나머지 프로미스를 기다리지 않고 즉시 종료한다.

### 45.6.3. Promise.race

`Promise.race`는 `Promise.all`과 동일하게 프로미스를 요소로 갖는 배열 등의 이터러블을 인수로 받는다. 차이점은 모든 프로미스가 fulfilled 상태가 되는 것을 기다리는 것이 아니라 가장 먼저 fulfilled 상태가 된 프로미스의 처리 결과를 resolve하는 새로운 프로미스를 리턴한다.  
`Promise.all`과 마찬가지로 프로미스가 하나라도 rejected가 되면 즉시 종료한다.

### 45.6.4. Promise.allSettled

프로미스를 요소로 갖는 배열 등의 이터러블을 인수로 전달받는다. 전달받은 프로미스가 모두 settled 상태(fulfilled 또는 rejected)가 되면 처리 결과를 배열로 리턴한다.  
리턴한 배열에는 상태와 관계없이 모든 프로미스들의 처리 결과가 담겨 있는데, 처리 결과를 나타내는 객체는 다음과 같다.

- fulfilled인 경우: 처리 상태를 나타내는 status 프로퍼티와 결과를 나타내는 value 프로퍼티
- rejected인 경우: 처리 상태를 나타내는 status 프로퍼티와 에러를 나타내는 reason 프로퍼티

## 45.7. 마이크로태스크 큐

```js
setTimeout(() => console.log(1), 0)

Promise.resolve()
  .then(() => console.log(2))
  .then(() => console.log(3))

// 2
// 3
// 1
```

프로미스의 후속 처리 메서드의 콜백 함수는 태스크 큐가 아니라 마이크로태스크 큐에 저장된다.

마이크로태스크 큐는 태스크 큐와는 별도의 큐로, 프로미스의 후속 처리 메서드의 콜백 함수가 일시 저장된다. 그 외의 비동기 함수의 콜백 함수나 이벤트 핸들러는 태스크 큐에 일시 저장된다.

**마이크로태스크 큐는 태스크 큐보다 우선순위가 높다.** 따라서, 이벤트 루프는 콜 스택이 비면 마이크로태스크 큐에서 대기하고 있는 함수를 가져와 실행하고, 마이크로태스크 큐가 비면 태스크 큐에 대기하고 있는 함수를 가져와 실행한다.

## 45.8. fetch

fetch 함수는 XMLHttpRequest 객체와 마찬가지로 HTTP 요청 전송 기능을 제공하는 클라이언트 사이드 Web API다. 사용법이 더 간단하고 프로미스를 지원해 비동기 처리를 위한 콜백 패턴의 단점에서 자유롭다.

fetch 함수는 HTTP 응답을 나타내는 Response 객체를 래핑한 Promise 객체를 리턴한다.

fetch를 사용할 때는 에러 처리에 주의해야 한다.

```js
fetch(wrongUrl) // 잘못된 URL이 지정되어 404 에러 발생
  .then(() => console.log('ok'))
  .catch(() => console.log('error'))

// 'ok'
```

404에러가 발생하며 catch에 'error'가 출력될 것 같지만 그렇지 않다.  
fetch 함수가 리턴하는 프로미스는 404, 500 같은 HTTP 에러를 reject하지 않고 불리언 타입의 ok 상태를 false로 설정한 Response 객체를 resolve한다. 오프라인 등의 네트워크 장애나 CORS에러로 요청이 완료되지 못한 경우만 프로미스를 reject한다.

따라서 fetch가 리턴한 프로미스가 resolve한 불리언 타입의 ok 상태를 확인해 명시적으로 에러를 처리할 필요가 있다.

```js
fetch(wrongUrl)
  .then((response) => {
    if (!response.ok) throw new Error(response.statusText)
    return response.json()
  })
  .then((todo) => console.log(todo))
  .catch((err) => console.error(err))
```

`axios`는 모든 HTTP 에러를 reject하는 프로미스를 리턴한다. 따라서 모든 에러를 catch에서 처리할 수 있어 편하다.
